# vi: set ft=ruby :

# Set up a scratch VM

$provision = <<PROVISION

sudo apt-get update
sudo apt-get install -y python-virtualenv

cd /vagrant
virtualenv --python=python3 venv

venv/bin/pip install -r requirements.txt

PROVISION

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 5000, host: 5000  # for flask devserver

    config.vm.provider"virtualbox" do |vb|
        vb.name = "Flask Authlib experiment"
        vb.memory = 1024
        vb.cpus = 1
    end

    config.vm.provision :shell, inline: $provision, privileged: false

end

