# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update
sudo apt-get upgrade

# sudo apt-get install -y git
# bootstrap a recent pip3
# sudo apt-get install -y python3-pip
# sudo -H pip3 install --upgrade pip

sudo apt-get install -y curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

SCRIPT


VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"
    # config.vm.network "forwarded_port", guest: 5000, host: 5000  # no flask, yet
    config.vm.network "forwarded_port", guest: 8080, host: 8080

    config.vm.provider "virtualbox" do |vb|
        vb.name = "modernjs"
        vb.memory = 2048
        vb.cpus = 1
    end

    config.vm.provision :shell, inline: $provision, privileged: false
end
