# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "ansible-play"

  config.vm.provider :virtualbox do |v|
    v.name = "ansible-play"
    v.memory = 512
    v.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "__provision__/playbook.yml"
  end

end
