# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update

sudo apt-get install -y git

# bootstrap a recent pip3
sudo apt-get install -y python3-pip
sudo -H pip3 install --upgrade pip

sudo apt-get install -y npm
sudo npm install -g vue-cli

# this gets us up to `vue init webpack vueapp01` in the tutorial

SCRIPT



VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "vue-tutorial"
        vb.memory = 2048
        vb.cpus = 1
    end

    config.vm.provision :shell, inline: $provision, privileged: false
end
