services:

  tailwindcss:
    build:
      context: .
      dockerfile: Dockerfile.tailwindcss
    volumes:
      - /home/dws/github/davewsmith/play/tailwind-docker:/app
    stdin_open: true  # this bit of magic was painful to find
    command:
      - bash
      - -c
      - |
          tailwindcss -i tailwind.css -o style.css --watch
