services:

  tailwindcss:
    build:
      context: .
      dockerfile: Dockerfile.tailwindcss
    volumes:
      - .:/app
    command:
      - bash
      - -c
      - |
          tailwindcss -i tailwind.css -o style.css --watch=always

  http:
    build:
      context: .
      dockerfile: Dockerfile.http
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command:
      - bash
      - -c
      - |
          python3 -m http.server
