# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update
# sudo apt-get upgrade
# sudo apt-get install -y git
sudo apt-get install -y python-virtualenv graphviz

cd /vagrant
virtualenv --python=python3 venv
venv/bin/pip install --upgrade pip
venv/bin/pip install -r requirements.txt

SCRIPT


VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/bionic64"  # Ubuntu 18.04 LTS

    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "flask-graphviz"
        vb.memory = 2048
        vb.cpus = 1
    end

    config.vm.provision :shell, inline: $provision, privileged: false
end
