Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"  # Ubuntu 18.04 LTS

    # config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "FlaskSQLAlchemy"
        vb.memory = 1024  # to simulate a Raspberry Pi deployment
        vb.cpus = 1
    end

    config.vm.provision "shell", :path => "provision.sh"
end
