blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    url: https://github.com/AnswerDotAI/fasthtml/discussions
    about: You can ask for help here!
  - name: Join our Discord
    url: https://discord.gg/qcXvcxMhdP
    about: Join our community on Discord!
