# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update

# sudo apt-get install -y git

sudo apt-get install -y python3-pip
# bootstrap a recent pip3
sudo -H pip3 install --upgrade pip

# Install matplotlib and some extras
sudo -H pip3 install matplotlib numpy scipy sklearn pandas seaborn

# And finally, Flask
sudo -H pip3 install Flask

SCRIPT



VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "matplotlib-flask"
        vb.memory = 2048
        vb.cpus = 1
    end

    config.vm.provision :shell, inline: $provision, privileged: false
end
