# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update

# bootstrap a recent pip3
# sudo apt-get install -y python3-pip
# sudo -H pip3 install --upgrade pip

sudo apt-get install -y build-essential texlive python-virtualenv

virtualenv --python=python3 venv
venv/bin/pip install flask latex

SCRIPT



VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "latex hackery"
        vb.memory = 2048
        vb.cpus = 1
    end

    config.vm.provision :shell, inline: $provision, privileged: false
end
