# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update

sudo apt-get install -y python-virtualenv redis-server
cd /vagrant
virtualenv --python=python3 venv
venv/bin/pip install redis

echo ":set hlsearch noincsearch noai sw=4 ts=40" >> ~/.vimrc

SCRIPT


Vagrant.configure("2") do |config|
    config.vm.define "RedisExperiment"
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "RedisExperiment"
        vb.memory = 1024
        vb.cpus = 1
    end


    config.vm.provision :shell, inline: $provision, privileged: false
end

