# vi: set ft=ruby :

$provision = <<SCRIPT
sudo apt-get update
sudo apt-get install -y python3.8-venv redis-server
cd /vagrant
python3 -m venv venv
venv/bin/pip install redis

echo ":set hlsearch noincsearch noai sw=4 ts=40" >> ~/.vimrc

SCRIPT


Vagrant.configure("2") do |config|
    config.vm.define "RedisPlaygound"
    config.vm.box = "ubuntu/focal64"  # 22.04 LTS
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |vb|
        vb.name = "RedisPlayground"
        vb.memory = 1024
        vb.cpus = 1
    end


    config.vm.provision :shell, inline: $provision, privileged: false
end

