on:
  push:
    # tags:
    #   - '*'

jobs:
  echo-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Echo
        run: |
            echo "I've been triggered!"
            echo "github.ref_name: ${{ github.ref_name }}"
    
